### ISSUE TITLE
Make the search icon visible above the search field

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#1]
<img width="293" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/07e1e2bb-fa35-4fff-bf2e-19f2b673fea9">

<img width="275" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/f2a7e06c-55d1-4ae1-9331-1e0de14b8c23">

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue, can you assign me this?

**Comment by RSMJAN** [comment]
hey,
I want to work on this issue.

**Comment by FL45H404** [comment]
hey , I want to work on that issue., could you assign me?

**Comment by JoshLamptey** [comment]
> hey , I want to work on that issue., could you assign me?

bro this is like the third issue i am seeing you on. relax my guy

**Comment by JoshLamptey** [comment]
hey i would like to work on this issue please

**Comment by alanansari** [comment]
The search icon is visible if the feed is dragged down. That must be moved on top of the search bar.

**Comment by JoshLamptey** [comment]
I'm at work ill get to this when I get home

**Comment by FL45H404** [comment]
hey @alanansari Is it ok?
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/70277710/41e9a458-a63d-44c5-a2a9-cb0108a5647b)

**Comment by FL45H404** [comment]
Bro how to add hacktoberfest-accepted label.

**Comment by JoshLamptey** [comment]
Check the issue template and then labels
