### ISSUE TITLE
Add indicator for file(image/video) upload: progress bar

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#14]
<img width="404" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/e3c6426a-c42c-4ff4-9c09-f5cd340f52bb">
<br>
Add an indicator for file uploading when creating a tweet with image/video.

**Comment by Umang070** [comment]
I can work on this task

**Comment by Umang070** [comment]
![Capture](https://github.com/Tweeter-Org/tweeter-frontend/assets/65073407/9967bee2-6c67-4e1e-81a8-92d0da8a82c7)
Do you want something like this as a progress bar ? and it is just a stimulation of progress bar.

**Comment by alanansari** [comment]
> ![Capture](https://user-images.githubusercontent.com/65073407/273333447-9967bee2-6c67-4e1e-81a8-92d0da8a82c7.PNG) Do you want something like this as a progress bar ? and it is just a stimulation of progress bar.

Yes, something like this would be perfect :)
