### ISSUE TITLE
Stuck on loader while visiting the site

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#17]
<img width="941" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/49addeb3-cd81-4eaf-9203-1f9e53792cc1">
<br>
- State management of the loader
- Make the rest of the site not respond to user interaction while loader is displayed

**Comment by RKOsvk** [comment]
hello, can you assign me to this issue?

**Comment by alanansari** [comment]
<img width="950" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/3428088a-4083-4412-a0d7-75fd97997873">

**Comment by alanansari** [comment]
@RKOsvk u still working on this?

**Comment by RKOsvk** [comment]
yes i am still working on it

**Comment by RKOsvk** [comment]
Is there any steps to reproduce?

**Comment by alanansari** [comment]
Was solved
