### ISSUE TITLE
[FIX] navigation to profile page

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#19]
<img width="898" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/24bfc57f-9dae-497d-a99d-f23d4881dbb7">
<br>
- Visiting the profile page sometimes shows a blank page

**Comment by gurjott** [comment]
please assign me

**Comment by tmatheas** [comment]
#26
