### ISSUE TITLE
Change the date format to dd-mm-yyyy in profile section

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#2]
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/08eb53f1-e045-4879-a448-c935d10fccde)

**Comment by uditi1002** [comment]
can i be assigned to this?

**Comment by RSMJAN** [comment]
heyy,
I want to work on this issue.
can you assign it to me?
