### ISSUE TITLE
Blank Picture on starting of messaging page

### ISSUE THREAD

**Issue by Umang070** [Tweeter-Org/tweeter-frontend#20]
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/65073407/441ebbc4-0c43-43d8-984b-4d5dc00ee850)
Is it a bug or it is developed like this?

**Comment by alanansari** [comment]
I suppose it's a bug.. can you fix this along with the CSS of the chatting window? I wanted it to be responsive.
