### ISSUE TITLE
The website name is not set for tabs in browser

### ISSUE THREAD

**Issue by MahendraDani** [Tweeter-Org/tweeter-frontend#23]
## Description
Instead of website's name, `React App` is shown on browser tabs.
Please refer to the screenshots below.
![Capture_1](https://github.com/Tweeter-Org/tweeter-frontend/assets/116940083/24103837-caf1-44f3-94db-5b2d0f810e15)
![Screenshot (22)](https://github.com/Tweeter-Org/tweeter-frontend/assets/116940083/002340b6-77f1-450b-ae0b-fa89b56f6823)

## Proposed solution
The name should be changed to `Tweeter`.

I would like to work on this issue

**Comment by alanansari** [comment]
Change it to Tweeter but also apply the favicon as 'T' the same as in the title.

**Comment by MahendraDani** [comment]
@alanansari 
When trying to setup the project locally. After running `npm install` I am getting the following error
```
npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: airbnb-prop-types@2.16.0
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   22 more (@fortawesome/react-fontawesome, @react-aria/ssr, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN node_modules/airbnb-prop-types
npm WARN   airbnb-prop-types@"^2.15.0" from react-outside-click-handler@1.3.0        
npm WARN   node_modules/react-outside-click-handler
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
npm WARN   node_modules/airbnb-prop-types
npm WARN     airbnb-prop-types@"^2.15.0" from react-outside-click-handler@1.3.0
npm WARN     node_modules/react-outside-click-handler
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: emoji-mart@3.0.1
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   22 more (@fortawesome/react-fontawesome, @react-aria/ssr, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0" from emoji-mart@3.0.1
npm WARN node_modules/emoji-mart
npm WARN   emoji-mart@"3.0.1" from react-input-emoji@4.3.0
npm WARN   node_modules/react-input-emoji
npm WARN
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0" from emoji-mart@3.0.1
npm WARN   node_modules/emoji-mart
npm WARN     emoji-mart@"3.0.1" from react-input-emoji@4.3.0
npm WARN     node_modules/react-input-emoji
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-hashtag@2.1.2
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@">=16.3" from @fortawesome/react-fontawesome@0.2.0
npm ERR!   node_modules/@fortawesome/react-fontawesome
npm ERR!     @fortawesome/react-fontawesome@"^0.2.0" from the root project
npm ERR!   21 more (@react-aria/ssr, @reduxjs/toolkit, @restart/hooks, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.7.0" from react-hashtag@2.1.2
npm ERR! node_modules/react-hashtag
npm ERR!   react-hashtag@"^2.1.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.7.0" from react-hashtag@2.1.2
npm ERR!   node_modules/react-hashtag
npm ERR!     react-hashtag@"^2.1.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\dell\AppData\Local\npm-cache\_logs\2023-10-08T04_07_18_440Z-eresolve-report.txt
```

Please help me fix this error!

**Comment by alanansari** [comment]
> @alanansari When trying to setup the project locally. After running `npm install` I am getting the following error
> 
> ```
> npm install
> npm WARN ERESOLVE overriding peer dependency
> npm WARN While resolving: airbnb-prop-types@2.16.0
> npm WARN Found: react@18.2.0
> npm WARN node_modules/react
> npm WARN   react@"^18.2.0" from the root project
> npm WARN   22 more (@fortawesome/react-fontawesome, @react-aria/ssr, ...)
> npm WARN
> npm WARN Could not resolve dependency:
> npm WARN peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
> npm WARN node_modules/airbnb-prop-types
> npm WARN   airbnb-prop-types@"^2.15.0" from react-outside-click-handler@1.3.0        
> npm WARN   node_modules/react-outside-click-handler
> npm WARN
> npm WARN Conflicting peer dependency: react@16.14.0
> npm WARN node_modules/react
> npm WARN   peer react@"^0.14 || ^15.0.0 || ^16.0.0-alpha" from airbnb-prop-types@2.16.0
> npm WARN   node_modules/airbnb-prop-types
> npm WARN     airbnb-prop-types@"^2.15.0" from react-outside-click-handler@1.3.0
> npm WARN     node_modules/react-outside-click-handler
> npm WARN ERESOLVE overriding peer dependency
> npm WARN While resolving: emoji-mart@3.0.1
> npm WARN Found: react@18.2.0
> npm WARN node_modules/react
> npm WARN   react@"^18.2.0" from the root project
> npm WARN   22 more (@fortawesome/react-fontawesome, @react-aria/ssr, ...)
> npm WARN
> npm WARN Could not resolve dependency:
> npm WARN peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0" from emoji-mart@3.0.1
> npm WARN node_modules/emoji-mart
> npm WARN   emoji-mart@"3.0.1" from react-input-emoji@4.3.0
> npm WARN   node_modules/react-input-emoji
> npm WARN
> npm WARN Conflicting peer dependency: react@17.0.2
> npm WARN node_modules/react
> npm WARN   peer react@"^0.14.0 || ^15.0.0-0 || ^16.0.0 || ^17.0.0" from emoji-mart@3.0.1
> npm WARN   node_modules/emoji-mart
> npm WARN     emoji-mart@"3.0.1" from react-input-emoji@4.3.0
> npm WARN     node_modules/react-input-emoji
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR!
> npm ERR! While resolving: react-hashtag@2.1.2
> npm ERR! Found: react@18.2.0
> npm ERR! node_modules/react
> npm ERR!   react@"^18.2.0" from the root project
> npm ERR!   peer react@">=16.3" from @fortawesome/react-fontawesome@0.2.0
> npm ERR!   node_modules/@fortawesome/react-fontawesome
> npm ERR!     @fortawesome/react-fontawesome@"^0.2.0" from the root project
> npm ERR!   21 more (@react-aria/ssr, @reduxjs/toolkit, @restart/hooks, ...)
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.7.0" from react-hashtag@2.1.2
> npm ERR! node_modules/react-hashtag
> npm ERR!   react-hashtag@"^2.1.2" from the root project
> npm ERR!
> npm ERR! Conflicting peer dependency: react@16.14.0
> npm ERR! node_modules/react
> npm ERR!   peer react@"^16.7.0" from react-hashtag@2.1.2
> npm ERR!   node_modules/react-hashtag
> npm ERR!     react-hashtag@"^2.1.2" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR! 
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! C:\Users\dell\AppData\Local\npm-cache\_logs\2023-10-08T04_07_18_440Z-eresolve-report.txt
> ```
> 
> Please help me fix this error!
try these for project setup and dependency installation:
npm config set legacy-peer-deps true
npm i

**Comment by ujju2000** [comment]
can i work on this issue if it's open ?

**Comment by MahendraDani** [comment]
@ujju2000 I am working on this issue.
Please checkout other open issues.
Thanks!
