### ISSUE TITLE
[FIX] Scroll on search results y overflow

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#24]
<img width="275" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/d7eefcb1-de67-44cf-bb90-6cefac0de106">
<br>
- Make search results scrollable and 70% of device height.<br>
- Also, fix the Responsive CSS of search.

**Comment by eugeneanokye99** [comment]
Please assign me

**Comment by FL45H404** [comment]
hey @alanansari , I want to work on it could you assign me
