### ISSUE TITLE
Remove bubble overlay on username hover on tweets.

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#3]
<img width="162" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/fc268816-1985-4ce5-87ad-ab081e7f17a0">
<br>
remove the expansion of username on hover and apply the linking to it directly.

**Comment by imSyntn** [comment]
please assign this issue to me...

**Comment by imSyntn** [comment]
Starting from the begining
