### ISSUE TITLE
Creating landing page for this project

### ISSUE THREAD

**Issue by roxoho** [Tweeter-Org/tweeter-frontend#30]
Hi, I think adding a landing page to this project would make it look good.

I am willing to work on this, if you want to add a landing page for your project.

**Comment by alanansari** [comment]
Where do you want to put a landing page?

**Comment by roxoho** [comment]
I am thinking the users should first get to know about this project, then they can move on to login.

We can use existing screenshots and information

**Comment by alanansari** [comment]
Can you make a crousel in the login/signup and forgot password pages at the side of the form for this..
Like 50% of the page for the crousel giving an overview of the features provided by this project and rest 50% for login/signup forms?

**Comment by roxoho** [comment]
Ok, it will take time but I will try my best

**Comment by alanansari** [comment]
> Ok, it will take time but I will try my best

Take time 👍
Eager to see what u do :)

**Comment by roxoho** [comment]
Hey, I think I lack the skill and time to do this task currently.

Sorry for the inconvenience, I am closing this issue.
