### ISSUE TITLE
[Fix] just tapping on the comment increments the counter

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#33]
<img width="101" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/8d6850f0-b992-4217-8f13-496c79b9ae88">
- Make it such that it increments only after comment is posted.

**Comment by Surajit0573** [comment]
I can fix this. Assign it to me !!

**Comment by saura8668** [comment]
hey @alanansari can u assign me this issue?

**Comment by saura8668** [comment]
Hey @alanansari fix the "just tapping on the comment increments the counter" issue and created the pull request. Please review.
