### ISSUE TITLE
Disable interactivity throughout the webpage when loader appears.

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#34]

**Comment by VividhPandey003** [comment]
Hey could you please tell me the prerequisites/tech stack required for this. I am interested in working on this issue

**Comment by alanansari** [comment]
> Hey could you please tell me the prerequisites/tech stack required for this. I am interested in working on this issue

Reactjs is the primary tech stack

**Comment by VividhPandey003** [comment]
Could you please assign this issue to me

**Comment by sikehish** [comment]
Hi I would like to take this up. I'd approach this issue by making use of a boolean state. Hope that would be okay. If yes, can you assign it to me?

**Comment by sikehish** [comment]
@alanansari could you explain what the issue actually is? The issue lacks clarity

**Comment by sikehish** [comment]
Hi @alanansari . Ive created a [PR](https://github.com/Tweeter-Org/tweeter-frontend/pull/48), addressing this issue. Let me know if any changes are to be made.
