### ISSUE TITLE
Error during the installion on windows 10

### ISSUE THREAD

**Issue by codewithsonyy** [Tweeter-Org/tweeter-frontend#40]
When I followed the instruction to install the frontend which was rather straightforward, I got error.
Is there anyone meet the same problem and can solve it?

![Screenshot (295)](https://github.com/Tweeter-Org/tweeter-frontend/assets/114895266/7228547b-dd47-4d73-93f7-8d94b8691ee3)

**Comment by saura8668** [comment]
try "npm install --legacy-peer-deps".

**Comment by codewithsonyy** [comment]
> "npm install --legacy-peer-deps"

wow it is working! Thank you so much!
