### ISSUE TITLE
Blank page if no user found

### ISSUE THREAD

**Issue by Umang070** [Tweeter-Org/tweeter-frontend#45]
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/65073407/230c5a77-1dbc-454e-a890-0ff0761e5103)
this is the tweet that includes hashtags and mentions but when I clicked on admin it showed me the page which I attached below
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/65073407/12996467-1ee8-4462-9d2e-9c62b7f9e666)
is this bug or is it implemented in this way? @alanansari

**Comment by alanansari** [comment]
Yes, its a bug.

**Comment by sikehish** [comment]
I'd love to take this up.

**Comment by sikehish** [comment]
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/90673701/5741a1b1-bf08-40dc-b232-7253ead803b4)
For some reason, everything's loading, but nothing's rendering. I not able to login/signup as well. Im assuming there's some issue with the render deployment on the backend

**Comment by sikehish** [comment]
Hi @alanansari . The issue is solved. Ive created a [PR](https://github.com/Tweeter-Org/tweeter-frontend/pull/47). Please review it and let me know.
