### ISSUE TITLE
Username overlap on followers/following list

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#7]
<img width="462" alt="image" src="https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/c8a662db-392a-4e66-8fae-d9b95edfcd34">

**Comment by tvermaashutosh** [comment]
@alanansari Assign me this issue.

**Comment by tmatheas** [comment]
@alanansari assign me this issue

**Comment by alanansari** [comment]
> @alanansari assign me this issue

It's already solved.. please see other issues

**Comment by tmatheas** [comment]
> > @alanansari assign me this issue
> 
> It's already solved.. please see other issues

Yeah I have only solved this. Just to add it to my name
