### ISSUE TITLE
View tweets and replies on profile visit itself

### ISSUE THREAD

**Issue by alanansari** [Tweeter-Org/tweeter-frontend#9]
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/cec2e943-f4b1-4195-8d64-8b429d2b5483)
<br>
![image](https://github.com/Tweeter-Org/tweeter-frontend/assets/22475370/b1a258d3-248a-4fec-9649-f690d8f3e5ed)
User has to click on the tweets and replies tab to see it upon visit make it such that it gets an active state upon visit.

**Comment by jonoliver1997** [comment]
I would like to work on this issue :)

**Comment by alanansari** [comment]
@jonoliver1997 are you still working on this?

**Comment by jonoliver1997** [comment]
Yes I am! Will try to finish it asap and send pr :)
